// Basic tests for the lexer/parser.

caterwaul.clone('std figment')(function () {
  eq('foo', qs[foo]),
  where*[eq(s, t) = l[sp = caterwaul.figment.parse(s).serialize(), tp = t.serialize()][s === t || null['#{s} should have been equal to #{t}']]]})();
// Generated by SDoc 
