// Basic tests for the lexer/parser.

caterwaul.clone('std figment')(function () {
  eq('foo', qs[foo]),
  eq('_foo_', qs[_foo_]),
  eq('(_foo_)', qse[qg[_foo_]]),
  where*[count    = 0,
         eq(s, t) = l[sp = caterwaul.figment.parse(s).toString(), tp = t.serialize()][s === t || null['#{s} should have been equal to #{t} (count #{++count})']]]})();
// Generated by SDoc 
