// Caterwaul std integration.

console.log('starting test caterwaul-std');
caterwaul.clone('std')(function () {
  defsubst[_x == _y][l[xc = _x, yc = _y][xc === yc || null['#{xc} should === #{yc}']]];
  var fig = caterwaul.clone('fig.semantics fig.parser').after(caterwaul.clone('std seq continuation'));

  fig('x + 1, where[x = 10]') == 11;
  fig('f(_) / cps[_ + 3]', {f: fn[g][g(9)]}) == 12;
  fig('l[f x = x + 10] [f 5]') == 15;
})();
// Generated by SDoc 
