// Tests for line and block comments (lexer tests).

caterwaul.clone('std seq continuation figment')(function () {
  eq('foo', 'foo'),
  eq('foo - Bar', 'foo  '),
  eq('-foo - Bar', '-foo  '),

  eq('foo / Bar', 'foo  '),
  eq('/foo / Bar', '/foo  '),

  eq('Foo bar bif\n\nfoo', 'foo'),
  eq('| var x = 10;\ny = 5;\n\nbif + bar', 'bif + bar'),

  eq('foo\n\nBar bif\n\nbaz', 'foo\nbaz'),
  eq('foo - Bar bif\nbaz', 'foo  baz'),
  eq('foo- Bar bif\nbaz', 'foo baz'),
  eq('foo3/ Bar\n\nBaz', 'foo3 '),

  where*[equal(a, b) = a === b || null['#{a} should === #{b}'],
         eq(s, t)    = equal(caterwaul.figment.lex(s) /re[_.serialize ? _.serialize() : _], t)]})();
// Generated by SDoc 
