// Grouping construct tests.

console.log('starting test grouping');
caterwaul.clone('std seq continuation')(function () {
  eq('(foo)', qse[qg[foo]]),
  eq('[foo]', qs[[foo]]),
  eq('{foo:bar}', qs[{foo:bar}]),

  eq('(foo) + (bar)', qse[qg[foo] + qg[bar]]),
  eq('[foo] + [bar]', qs[[foo] + [bar]]),

  eq('([foo])', qse[qg[[foo]]]),
  eq('([[[[foo]]]])', qse[qg[[[[[foo]]]]]]),
  eq('([([(foo)])])', qse[qg[[qg[[qg[foo]]]]]]),

  where*[figment     = caterwaul.clone('fig.parser'),
         equal(a, b) = a === b || null['#{a} should === #{b}'],
         eq(s, t)    = equal(qs[_x].replace({_x: figment.parse(s)}).serialize(), t.serialize())]})();
// Generated by SDoc 
