// A test for require() within node.js

var got_called = false;

var compiler = caterwaul.clone('fig');

compiler.configure(caterwaul.clone('std')(function () {
  var m = this.init;
  this.method('init', fn_[
    console.log('compiling #{Array.prototype.slice.call(arguments).join(", ")}'),
    m.apply(this, arguments) /se[console.log('returned #{_}')]]);
}));

compiler.require('test/helloworld.fig', function () {
  got_called = true;
  this.hello_world === 'hello world!' || null['fail: expected hello world, but got #{this.hello_world}'];
});
got_called || null['fail: callback was never invoked'];
// Generated by SDoc 
