// A test for require() within node.js

var got_called = false;
var compiler = caterwaul.clone('fig');

compiler.require('test/helloworld.fig', function () {
  got_called = true;
  this.hello_world === 'hello world!' || null['fail: expected hello world, but got ' + this.hello_world];
});

got_called || null['fail: callback was never invoked'];
// Generated by SDoc 
