// Standard library for Figment | Spencer Tipping
// Licensed under the terms of the MIT source code license

// Introduction.
// Caterwaul's standard library is built around the syntactic patterns required by Javascript. But Figment isn't constrained by the same patterns that Javascript is, so more idiomatic constructs
// can be written. Many of the patterns are still there however.

// Quotation.
// This is preserved as-is. I briefly considered using % rather than q, but qs[] is much easier to read than %s[]. Because Firefox can't bork Figment source there is no need for the qg[] macro --
// regular parens are never erased prior to quotation.

// TODO
// Generated by SDoc 
